[package]
name = "crater-tree"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
failure = "0.1.1"
tempdir = "0.3.7"
cargo_metadata = "0.5.4"
rayon = "1.0.1"
